version: 1.2
workflows:
- name: PhysicalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/PhysicalPhasing.wdl
- name: PhysicalPhasing_XYM
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/PhysicalPhasing_XYM.wdl
- name: StatisticalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing.wdl
- name: StatisticalPhasing_Stage0_CreateShards
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage0_CreateShards.wdl
- name: StatisticalPhasing_Stage1_FilterAndConcatVcfs
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage1_FilterAndConcatVcfs.wdl
- name: StatisticalPhasing_Stage2_FixVariantCollisions
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage2_FixVariantCollisions.wdl
- name: StatisticalPhasing_Stage3_GatherSitesAndChunk
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage3_GatherSitesAndChunk.wdl
- name: StatisticalPhasing_Stage4_Shapeit4Phase
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage4_Shapeit4Phase.wdl
- name: StatisticalPhasing_Stage5_ShapeitLigate
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing_Stage5_ShapeitLigate.wdl
- name: PanGeniePanelCreation
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/imputation/PanGeniePanelCreation.wdl
- name: BubblePanelCreation
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/imputation/BubblePanelCreation.wdl
- name: PostprocessBubblePanel
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/imputation/PostprocessBubblePanel.wdl
- name: GLIMPSE2BatchedCaseShardedSingleBatch
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/imputation/GLIMPSE2BatchedCaseShardedSingleBatch.wdl
- name: VcfdistEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phasing/VcfdistEvaluation.wdl
- name: GLIMPSE2Concordance
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/imputation/GLIMPSE2Concordance.wdl
- name: GLIMPSE2MendelianConsistency
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/imputation/GLIMPSE2MendelianConsistency.wdl
- name: HierarchicallyMergeVcfs
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/HierarchicallyMergeVcfs.wdl
- name: MultilevelHierarchicallyMergeVcfs
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/MultilevelHierarchicallyMergeVcfs.wdl
- name: MultilevelHierarchicallyMergeVcfsStreaming
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/MultilevelHierarchicallyMergeVcfsStreaming.wdl
- name: ConcatVcfs
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/ConcatVcfs.wdl
- name: TransferAWSOpenData
  subclass: wdl
  primaryDescriptorPath: /wdl/TransferAWSOpenData.wdl
