version: 1.2
workflows:
- name: StatisticalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing.wdl
- name: VcfdistAndSwitchEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phasing/VcfdistAndSwitchEvaluation.wdl
