version: 1.2
workflows:
- name: StatisticalPhasing
  subclass: wdl
  primaryDescriptorPath: /wdl/methods/phasing/StatisticalPhasing.wdl
- name: VcfdistEvaluation
  subclass: wdl
  primaryDescriptorPath: /wdl/evaluation/phasing/VcfdistEvaluation.wdl
