#!/usr/bin/env python

# Based on https://github.com/eblerjana/pangenie/blob/master/pipelines/run-from-callset/scripts/convert-to-biallelic.py, but with modifications for GLIMPSE2 input (bubbles split to biallelic).
# Code + test code + summary generated with Gemini Pro.

# Background Motivation and Terminology
#   The primary goal of this work was to post-process phased variant calls output by GLIMPSE2, specifically translating complex variation graph structures back into their foundational components while accurately handling phasing inconsistencies.
#   To understand the pipeline, we rely on a few specific bioinformatics concepts:
#     Bubbles: Complex multiallelic regions within a variation graph (like those generated by PanGenie) where the genomic sequence diverges into multiple possible paths before rejoining the reference.
#     Constituent Variants: The atomic components (individual SNVs or indels) that make up a specific path through a bubble.
#     Collisions: A biological impossibility introduced during phasing/imputation (e.g., by GLIMPSE2) where a sample is simultaneously assigned multiple, mutually exclusive bubble paths on the exact same haplotype.
#     GP (Genotype Posterior): A statistical array indicating the caller's confidence in a specific genotype call (e.g., 0|0, 0|1, 1|1).
#     The objective was to take GLIMPSE2's independent biallelic calls for these bubble paths, resolve any physical collisions using statistical and biological heuristics, and "pop" the paths back into a clean VCF of constituent variants.
# Differences from the Original PanGenie Script
#   The original PanGenie convert-to-biallelic.py script was designed for a simpler data topology. Our modified script introduces several major functional shifts:
#   Handling Biallelic Input: The original script expected a single multiallelic VCF record for an entire bubble. Because GLIMPSE2 splits paths into independent biallelic records, our script groups incoming lines by their genomic coordinate (POS) to reconstruct the bubble state dynamically.
#   In-Memory Projection: Rather than looping through a pre-defined multiallelic string, our script projects the Genotype (GT) and Genotype Quality (GQ) calls directly from the grouped biallelic records onto mapped constituent variants stored in memory.
#   Collision Resolution and Tracking: The original script assumed clean, unconflicted paths. Our script scans the grouped alleles for overlapping haplotype calls, identifies the mathematically or biologically optimal path, and annotates suboptimal paths.
#   Shared Constituent Handling: Our script seamlessly handles overlapping topologies where multiple diverging paths share the same underlying constituent variants, ensuring the final output accurately reflects the presence of a variant if any winning path traverses it.
# Key Design Choices
#   Throughout the session, we iterated on several design choices to ensure the pipeline was biologically sound and strictly adhered to VCF specifications.
#   Bypassing Upstream Merging: We chose to resolve collisions dynamically in memory rather than forcing an upstream merge using tools like bcftools norm. Standard VCF tools actively discard the phase conflicts (e.g., 1+2|0) that our script needs to observe to accurately score and resolve collisions.
#   Non-Destructive Annotation (The CL Field): Instead of destructively overwriting suboptimal colliding GT calls back to the reference (0), we implemented a custom FORMAT/CL (Collision) field. This preserves the raw GLIMPSE2 output for downstream analysis while clearly flagging which paths are invalid.
#   Strict VCFv4.2 Typing: We opted to define the CL field as a two-element Integer array (Number=2, Type=Integer) rather than a visual String (0|1). This forces comma separation (0,1), conforming to strict standard VCF parsing rules for arrays.
#   Tiered Tie-Breaking Logic: To resolve collisions, we implemented a three-tier heuristic. The pipeline prefers the path with the highest maximum GP. If tied, it falls back to a parsimony metric (preferring the path with the fewest constituent variants). If still tied, it defaults to a stable sort.
#   High-Resolution Collision Tracking: The CL array outputs specific integer codes (0=optimal, 1=lost by GP, 2=lost by parsimony, 3=lost by stable sort). When a constituent variant is supported by multiple losing paths, it receives the "best" score among its losers, providing granular traceability.

import sys
import argparse
from collections import defaultdict
import gzip

parser = argparse.ArgumentParser(prog='pop-glimpse2-max-gp.py', description='cat <multiallelic VCF> | python pop-glimpse2-max-gp.py <biallelic VCF>')
parser.add_argument('vcf', metavar='VCF', help='original VCF containing REF/ALT of each Variant ID.')
args = parser.parse_args()

def smart_open(filename):
    if filename.endswith('.gz'):
        return gzip.open(filename, 'rt')
    return open(filename, 'r')

# chromosome ->  ID -> [start, orig_ID, REF, ALT] per chromosome
chrom_to_variants = defaultdict(lambda: defaultdict(list))

# read the biallelic VCF containing REF/ALT for all variant IDs and store them
for line in smart_open(args.vcf):
    if line.startswith('#'):
        continue
    fields = line.strip().split('\t')
    info_field = { i.split('=')[0] : i.split('=')[1] for i in fields[7].split(';') if "=" in i}
    if 'ID' not in info_field: continue
    ids = info_field['ID'].split(',')
    chrom_to_variants[fields[0]][ids[0]] = [fields[1], fields[2], fields[3], fields[4]]

def process_group(group_lines):
    if not group_lines: return
    
    parsed_lines = [line.strip().split('\t') for line in group_lines]
    if len(parsed_lines[0]) <= 9:
        for fields in parsed_lines: print('\t'.join(fields))
        return
        
    num_samples = len(parsed_lines[0]) - 9
    
    # Inject CL to FORMAT if not present and pad sample fields with default 0,0
    for fields in parsed_lines:
        fmt = fields[8].split(':')
        if 'CL' not in fmt:
            fields[8] = fields[8] + ':CL'
            for s in range(num_samples):
                fields[9+s] += ':0,0'
                
    # Annotate collisions at the bubble level
    for s in range(num_samples):
        col = 9 + s
        hap0_ones = []
        hap1_ones = []
        
        for i, fields in enumerate(parsed_lines):
            fmt = fields[8].split(':')
            if 'GT' not in fmt: continue
            gt_idx = fmt.index('GT')
            sample_data = fields[col].split(':')
            gt = sample_data[gt_idx]
            
            if '|' not in gt: continue
            alleles = gt.split('|')
            
            info_field = { k.split('=')[0] : k.split('=')[1] for k in fields[7].split(';') if "=" in k}
            num_constituents = len(info_field.get('ID', '').replace(',', ':').split(':')) if 'ID' in info_field else 0
            
            gp_val = -1.0
            if 'GP' in fmt:
                gp_idx = fmt.index('GP')
                if gp_idx < len(sample_data) and sample_data[gp_idx] != '.':
                    gp_val = max([float(x) for x in sample_data[gp_idx].split(',')])
                    
            if alleles[0] == '1': hap0_ones.append((gp_val, num_constituents, i))
            if alleles[1] == '1': hap1_ones.append((gp_val, num_constituents, i))
            
        # Determine specific reason for collision loss on Hap0
        if len(hap0_ones) > 1:
            hap0_ones.sort(key=lambda x: (x[0], -x[1]), reverse=True)
            w_gp, w_const, _ = hap0_ones[0]
            
            for l_gp, l_const, i in hap0_ones[1:]:
                if w_gp > l_gp: reason = '1'
                elif w_const < l_const: reason = '2'
                else: reason = '3'
                
                fmt = parsed_lines[i][8].split(':')
                cl_idx = fmt.index('CL')
                s_data = parsed_lines[i][col].split(':')
                cl_vals = s_data[cl_idx].split(',')
                cl_vals[0] = reason
                s_data[cl_idx] = ','.join(cl_vals)
                parsed_lines[i][col] = ':'.join(s_data)
                
        # Determine specific reason for collision loss on Hap1
        if len(hap1_ones) > 1:
            hap1_ones.sort(key=lambda x: (x[0], -x[1]), reverse=True)
            w_gp, w_const, _ = hap1_ones[0]
            
            for l_gp, l_const, i in hap1_ones[1:]:
                if w_gp > l_gp: reason = '1'
                elif w_const < l_const: reason = '2'
                else: reason = '3'
                
                fmt = parsed_lines[i][8].split(':')
                cl_idx = fmt.index('CL')
                s_data = parsed_lines[i][col].split(':')
                cl_vals = s_data[cl_idx].split(',')
                cl_vals[1] = reason
                s_data[cl_idx] = ','.join(cl_vals)
                parsed_lines[i][col] = ':'.join(s_data)

    # Separate out unknown/passthrough records and collect known atomic targets
    all_atomic_vars = set()
    passthrough_lines = []
    
    for fields in parsed_lines:
        info_field = { i.split('=')[0] : i.split('=')[1] for i in fields[7].split(';') if "=" in i}
        if 'ID' not in info_field:
            passthrough_lines.append(fields)
            continue
            
        is_known = False
        for info_id in info_field['ID'].split(','):
            for j in info_id.split(':'):
                if j in chrom_to_variants[fields[0]]:
                    all_atomic_vars.add((j, int(chrom_to_variants[fields[0]][j][0])))
                    is_known = True
                    
        if not is_known:
            passthrough_lines.append(fields)

    # Output passthrough lines untouched
    for fields in passthrough_lines:
        print('\t'.join(fields))

    # Pop bubbles by projecting grouped GTs directly onto mapped atomic variants
    sorted_atomic_vars = list(all_atomic_vars)
    sorted_atomic_vars.sort(key=lambda x: x[1])
    
    for (var_id, coord) in sorted_atomic_vars:
        template_fields = None
        for fields in parsed_lines:
            info_field = { i.split('=')[0] : i.split('=')[1] for i in fields[7].split(';') if "=" in i}
            if 'ID' not in info_field: continue
            
            for info_id in info_field['ID'].split(','):
                if var_id in info_id.split(':'):
                    template_fields = fields
                    break
            if template_fields: break
            
        if not template_fields: continue
        
        vcf_line = list(template_fields[:9])
        vcf_line[1] = str(coord)
        vcf_line[2] = chrom_to_variants[template_fields[0]][var_id][1]
        vcf_line[3] = chrom_to_variants[template_fields[0]][var_id][2]
        vcf_line[4] = chrom_to_variants[template_fields[0]][var_id][3]
        
        template_info = { i.split('=')[0] : i.split('=')[1] for i in template_fields[7].split(';') if "=" in i}
        vcf_line[7] = 'ID=' + var_id
        for k,v in template_info.items():
            if k in ['MA', 'UK']:
                vcf_line[7] += ';' + k + '=' + v
                
        fmt_in = template_fields[8].split(':')
        fmt_out = ['GT']
        if 'GQ' in fmt_in: fmt_out.append('GQ')
        if 'CL' in fmt_in: fmt_out.append('CL')
        vcf_line[8] = ':'.join(fmt_out)
        
        for s in range(num_samples):
            col = 9 + s
            best_gq = '.'
            
            hap0_winner = False
            hap1_winner = False
            h0_losers = []
            h1_losers = []
            
            for fields in parsed_lines:
                info_field = { i.split('=')[0] : i.split('=')[1] for i in fields[7].split(';') if "=" in i}
                if 'ID' not in info_field: continue
                
                contains_var = False
                for info_id in info_field['ID'].split(','):
                    if var_id in info_id.split(':'):
                        contains_var = True
                        break
                        
                if contains_var:
                    f_fmt = fields[8].split(':')
                    s_data = fields[col].split(':')
                    
                    if 'GT' in f_fmt:
                        gt_idx = f_fmt.index('GT')
                        gt = s_data[gt_idx]
                        cl_idx = f_fmt.index('CL')
                        cl = s_data[cl_idx]
                        
                        if '|' in gt:
                            a_gt = gt.split('|')
                            a_cl = cl.split(',')
                            
                            if a_gt[0] == '1':
                                if a_cl[0] == '0': hap0_winner = True
                                else: h0_losers.append(int(a_cl[0]))
                                
                            if a_gt[1] == '1':
                                if a_cl[1] == '0': hap1_winner = True
                                else: h1_losers.append(int(a_cl[1]))
                                
                    if 'GQ' in f_fmt and 'GQ' in fmt_out:
                        gq_idx = f_fmt.index('GQ')
                        gq_val = s_data[gq_idx]
                        if gq_val != '.':
                            if best_gq == '.' or float(gq_val) > float(best_gq):
                                best_gq = gq_val
                                
            hap0_val = '1' if (hap0_winner or h0_losers) else '0'
            hap1_val = '1' if (hap1_winner or h1_losers) else '0'
            
            hap0_cl = '0' if hap0_winner or not h0_losers else str(max(h0_losers))
            hap1_cl = '0' if hap1_winner or not h1_losers else str(max(h1_losers))
            
            s_out = [f"{hap0_val}|{hap1_val}"]
            if 'GQ' in fmt_out: s_out.append(str(best_gq) if best_gq != '.' else '.')
            if 'CL' in fmt_out: s_out.append(f"{hap0_cl},{hap1_cl}")
            
            vcf_line.append(':'.join(s_out))
            
        print('\t'.join(vcf_line))

cl_header_added = False
current_pos = None
group = []

for line in sys.stdin:
    if line.startswith('#'):
        if any([i in line for i in ['INFO=<ID=AF', 'INFO=<ID=AK', 'FORMAT=<ID=GL', 'FORMAT=<ID=KC']]):
            continue
        if line.startswith('#CHROM') and not cl_header_added:
            print('##FORMAT=<ID=CL,Number=2,Type=Integer,Description="Collision indicator array (Hap0,Hap1): 0=optimal, 1=lost by GP, 2=lost by parsimony, 3=lost by stable sort">')
            cl_header_added = True
        print(line[:-1])
        continue
        
    fields = line.split('\t')
    if len(fields) < 2: continue
    pos = fields[1]
    
    if current_pos is None:
        current_pos = pos
        
    if pos != current_pos:
        process_group(group)
        group = [line]
        current_pos = pos
    else:
        group.append(line)
        
if group:
    process_group(group)
