#!/usr/bin/env python

# Based on https://github.com/eblerjana/pangenie/blob/master/pipelines/run-from-callset/scripts/convert-to-biallelic.py, but with modifications for GLIMPSE2 input (bubbles split to biallelic).
# Code + test code + summary generated with Gemini Pro.

# Background Motivation and Terminology
#   The primary goal of this work was to post-process phased variant calls output by GLIMPSE2, specifically translating complex variation graph structures back into their foundational components while accurately handling phasing inconsistencies and retaining important imputation annotations.
#   To understand the pipeline, we rely on a few specific bioinformatics concepts:
#     Bubbles: Complex multiallelic regions within a variation graph (like those generated by PanGenie) where the genomic sequence diverges into multiple possible paths before rejoining the reference.
#     Constituent Variants: The atomic components (individual SNVs or indels) that make up a specific path through a bubble.
#     Collisions: A biological impossibility introduced during phasing/imputation (e.g., by GLIMPSE2) where a sample is simultaneously assigned multiple, mutually exclusive bubble paths on the exact same haplotype.
#     GP (Genotype Posterior): A statistical array indicating the caller's confidence in a specific genotype call (e.g., 0|0, 0|1, 1|1).
#     The objective was to take GLIMPSE2's independent biallelic calls for these bubble paths, resolve any physical collisions using statistical and biological heuristics, and "pop" the paths back into a clean VCF of constituent variants.

# Differences from the Original PanGenie Script
#   The original PanGenie convert-to-biallelic.py script was designed for a simpler data topology. Our modified script introduces several major functional shifts:
#   Handling Biallelic Input: The original script expected a single multiallelic VCF record for an entire bubble. Because GLIMPSE2 splits paths into independent biallelic records, our script groups incoming lines by their genomic coordinate (POS) to reconstruct the bubble state dynamically.
#   In-Memory Projection: Rather than looping through a pre-defined multiallelic string, our script projects the Genotype (GT) and Genotype Quality (GQ) calls directly from the grouped biallelic records onto mapped constituent variants stored in memory.
#   Collision Resolution and Reversion: The original script assumed clean, unconflicted paths. Our script scans the grouped alleles for overlapping haplotype calls, identifies the mathematically or biologically optimal path, reverts the suboptimal GT calls to reference, and flags them.
#   Shared Constituent Handling: Our script seamlessly handles overlapping topologies where multiple diverging paths share the same underlying constituent variants. For statistical FORMAT fields like Dosage (DS) and Genotype Probabilities (GP), the constituent variant inherits the values from the highest-confidence path that traversed it.

# Key Design Choices
#   Throughout the session, we iterated on several design choices to ensure the pipeline was biologically sound and strictly adhered to VCF specifications.
#   Bypassing Upstream Merging: We chose to resolve collisions dynamically in memory rather than forcing an upstream merge using tools like bcftools norm. Standard VCF tools actively discard the phase conflicts (e.g., 1+2|0) that our script needs to observe to accurately score and resolve collisions.
#   Collision Reversion and Annotation (The CL Field): Suboptimal colliding GT calls are reverted back to the reference (0) to ensure a clean representation of the final resolved haplotype. Concurrently, a custom FORMAT/CL (Collision) field is added to annotate these reverted calls. This clearly flags which paths were originally proposed by the caller but were invalidated during tie-breaking.
#   Strict VCFv4.2 Typing: We opted to define the CL field as a two-element Integer array (Number=2, Type=Integer) rather than a visual String (0|1). This forces comma separation (0,1), conforming to strict standard VCF parsing rules for arrays.
#   Tiered Tie-Breaking Logic: To resolve collisions, we implemented a three-tier heuristic. The pipeline prefers the path with the highest maximum GP. If tied, it falls back to a parsimony metric (preferring the path with the fewest constituent variants). If still tied, it defaults to a stable sort.
#   High-Resolution Collision Tracking: The CL array outputs specific integer codes (0=optimal, 1=lost by GP, 2=lost by parsimony, 3=lost by stable sort). When a constituent variant is supported by multiple losing paths, it receives the "best" score among its losers, providing granular traceability.
#   Retaining GLIMPSE2 Annotations: The script explicitly maps and projects core GLIMPSE2 statistical annotations including Reference Allele Frequency (RAF), Alternate Allele Frequency (AF), Imputation Score (INFO), Estimated Dosage (DS), and Genotype Posteriors (GP).

import sys
import argparse
from collections import defaultdict
import gzip

parser = argparse.ArgumentParser(prog='pop-glimpse2-max-gp.py', description='cat <multiallelic VCF> | python pop-glimpse2-max-gp.py <biallelic VCF>')
parser.add_argument('vcf', metavar='VCF', help='original VCF containing REF/ALT of each Variant ID.')
args = parser.parse_args()

def smart_open(filename):
    if filename.endswith('.gz'):
        return gzip.open(filename, 'rt')
    return open(filename, 'r')

# chromosome ->  ID -> [start, orig_ID, REF, ALT] per chromosome
chrom_to_variants = defaultdict(lambda: defaultdict(list))

# read the biallelic VCF containing REF/ALT for all variant IDs and store them
for line in smart_open(args.vcf):
    if line.startswith('#'):
        continue
    fields = line.strip().split('\t')
    info_field = { i.split('=')[0] : i.split('=')[1] for i in fields[7].split(';') if "=" in i}
    if 'ID' not in info_field: continue
    ids = info_field['ID'].split(',')
    chrom_to_variants[fields[0]][ids[0]] = [fields[1], fields[2], fields[3], fields[4]]

def process_group(group_lines):
    if not group_lines: return
    
    parsed_lines = [line.strip().split('\t') for line in group_lines]
    if len(parsed_lines[0]) <= 9:
        for fields in parsed_lines: print('\t'.join(fields))
        return
        
    num_samples = len(parsed_lines[0]) - 9
    chrom = parsed_lines[0][0]
    
    # Pre-parse meta-data, formats, and sample objects to eliminate redundant string parsing bottlenecks
    line_meta = []
    samples_data = [[] for _ in range(len(parsed_lines))]
    gp_cache = [[-1.0] * num_samples for _ in range(len(parsed_lines))]
    
    for i, fields in enumerate(parsed_lines):
        info_field = { k.split('=')[0] : k.split('=')[1] for k in fields[7].split(';') if "=" in k}
        fmt = fields[8].split(':')
        
        added_cl = False
        if 'CL' not in fmt:
            fmt.append('CL')
            fields[8] = ':'.join(fmt)
            added_cl = True
            
        fmt_idx = {k: idx for idx, k in enumerate(fmt)}
        
        id_str = info_field.get('ID', '')
        num_constituents = len(id_str.replace(',', ':').split(':')) if id_str else 0
        
        atomic_vars = set()
        is_known = False
        if id_str:
            for info_id in id_str.split(','):
                for j in info_id.split(':'):
                    if j in chrom_to_variants[chrom]:
                        atomic_vars.add(j)
                        is_known = True
                        
        line_meta.append({
            'info': info_field,
            'fmt': fmt,
            'fmt_idx': fmt_idx,
            'ids': atomic_vars,
            'num_const': num_constituents,
            'is_known': is_known,
            'raw_fields': fields
        })
        
        gp_idx = fmt_idx.get('GP', -1)
        
        for s in range(num_samples):
            s_vals = fields[9+s].split(':')
            if added_cl and len(s_vals) < len(fmt):
                s_vals.append('0,0')
            samples_data[i].append(s_vals)
            
            if gp_idx != -1 and gp_idx < len(s_vals):
                gp_str = s_vals[gp_idx]
                if gp_str != '.':
                    gp_cache[i][s] = max([float(x) for x in gp_str.split(',')])

    # Annotate and revert collisions at the bubble level
    for s in range(num_samples):
        hap0_ones = []
        hap1_ones = []
        
        for i, meta in enumerate(line_meta):
            gt_idx = meta['fmt_idx'].get('GT', -1)
            if gt_idx == -1: continue
            gt = samples_data[i][s][gt_idx]
            if '|' not in gt: continue
            
            alleles = gt.split('|')
            gp_val = gp_cache[i][s]
            num_const = meta['num_const']
            
            if alleles[0] == '1': hap0_ones.append((gp_val, num_const, i))
            if alleles[1] == '1': hap1_ones.append((gp_val, num_const, i))
            
        # Determine specific reason for collision loss on Hap0 and revert GT
        if len(hap0_ones) > 1:
            hap0_ones.sort(key=lambda x: (x[0], -x[1]), reverse=True)
            w_gp, w_const, _ = hap0_ones[0]
            
            for l_gp, l_const, i in hap0_ones[1:]:
                if w_gp > l_gp: reason = '1'
                elif w_const < l_const: reason = '2'
                else: reason = '3'
                
                meta = line_meta[i]
                cl_idx = meta['fmt_idx']['CL']
                gt_idx = meta['fmt_idx']['GT']
                
                # Update CL
                cl_vals = samples_data[i][s][cl_idx].split(',')
                cl_vals[0] = reason
                samples_data[i][s][cl_idx] = ','.join(cl_vals)
                
                # Revert GT
                gt_vals = samples_data[i][s][gt_idx].split('|')
                gt_vals[0] = '0'
                samples_data[i][s][gt_idx] = '|'.join(gt_vals)
                
        # Determine specific reason for collision loss on Hap1 and revert GT
        if len(hap1_ones) > 1:
            hap1_ones.sort(key=lambda x: (x[0], -x[1]), reverse=True)
            w_gp, w_const, _ = hap1_ones[0]
            
            for l_gp, l_const, i in hap1_ones[1:]:
                if w_gp > l_gp: reason = '1'
                elif w_const < l_const: reason = '2'
                else: reason = '3'
                
                meta = line_meta[i]
                cl_idx = meta['fmt_idx']['CL']
                gt_idx = meta['fmt_idx']['GT']
                
                # Update CL
                cl_vals = samples_data[i][s][cl_idx].split(',')
                cl_vals[1] = reason
                samples_data[i][s][cl_idx] = ','.join(cl_vals)
                
                # Revert GT
                gt_vals = samples_data[i][s][gt_idx].split('|')
                gt_vals[1] = '0'
                samples_data[i][s][gt_idx] = '|'.join(gt_vals)

    # Output passthrough lines untouched (reverted GTs and CL annotations are preserved)
    all_atomic_vars = set()
    for i, meta in enumerate(line_meta):
        if not meta['is_known']:
            fields = meta['raw_fields']
            for s in range(num_samples):
                fields[9+s] = ':'.join(samples_data[i][s])
            print('\t'.join(fields))
        else:
            for j in meta['ids']:
                all_atomic_vars.add((j, int(chrom_to_variants[chrom][j][0])))

    # Pop bubbles by projecting grouped GTs directly onto mapped atomic variants
    sorted_atomic_vars = sorted(list(all_atomic_vars), key=lambda x: x[1])
    
    for var_id, coord in sorted_atomic_vars:
        template_i = -1
        for i, meta in enumerate(line_meta):
            if var_id in meta['ids']:
                template_i = i
                break
        if template_i == -1: continue
        
        t_meta = line_meta[template_i]
        t_fields = t_meta['raw_fields']
        
        vcf_line = list(t_fields[:9])
        vcf_line[1] = str(coord)
        vcf_line[2] = chrom_to_variants[chrom][var_id][1]
        vcf_line[3] = chrom_to_variants[chrom][var_id][2]
        vcf_line[4] = chrom_to_variants[chrom][var_id][3]
        
        new_info = [f"ID={var_id}"]
        for k in ['MA', 'UK', 'RAF', 'AF', 'INFO']:
            if k in t_meta['info']:
                new_info.append(f"{k}={t_meta['info'][k]}")
        vcf_line[7] = ';'.join(new_info)
            
        fmt_in = t_meta['fmt']
        fmt_out = ['GT']
        if 'DS' in fmt_in: fmt_out.append('DS')
        if 'GP' in fmt_in: fmt_out.append('GP')
        if 'GQ' in fmt_in: fmt_out.append('GQ')
        if 'CL' in fmt_in: fmt_out.append('CL')
        vcf_line[8] = ':'.join(fmt_out)
        
        # Pre-filter paths overlapping this specific constituent variant to bypass redundant loops
        lines_with_var = [i for i, meta in enumerate(line_meta) if var_id in meta['ids']]
        
        for s in range(num_samples):
            max_gp_for_ds_gp = -1.0
            best_ds = '.'
            best_gp = '.'
            best_gq = '.'
            
            hap0_winner = False
            hap1_winner = False
            h0_losers = []
            h1_losers = []
            
            for i in lines_with_var:
                meta = line_meta[i]
                s_vals = samples_data[i][s]
                
                gt_idx = meta['fmt_idx'].get('GT', -1)
                if gt_idx != -1:
                    gt = s_vals[gt_idx]
                    if '|' in gt:
                        a_gt = gt.split('|')
                        cl_idx = meta['fmt_idx']['CL']
                        a_cl = s_vals[cl_idx].split(',')
                        
                        if a_gt[0] == '1' and a_cl[0] == '0':
                            hap0_winner = True
                        elif a_cl[0] != '0':
                            h0_losers.append(int(a_cl[0]))
                            
                        if a_gt[1] == '1' and a_cl[1] == '0':
                            hap1_winner = True
                        elif a_cl[1] != '0':
                            h1_losers.append(int(a_cl[1]))
                
                curr_max_gp = gp_cache[i][s]
                if curr_max_gp > max_gp_for_ds_gp:
                    max_gp_for_ds_gp = curr_max_gp
                    ds_idx = meta['fmt_idx'].get('DS', -1)
                    if ds_idx != -1: best_ds = s_vals[ds_idx]
                    gp_idx = meta['fmt_idx'].get('GP', -1)
                    if gp_idx != -1: best_gp = s_vals[gp_idx]
                    
                gq_idx = meta['fmt_idx'].get('GQ', -1)
                if gq_idx != -1:
                    gq_val = s_vals[gq_idx]
                    if gq_val != '.':
                        if best_gq == '.' or float(gq_val) > float(best_gq):
                            best_gq = gq_val
                            
            # Reverted logic: GT is '1' only if a winning path supported it.
            hap0_val = '1' if hap0_winner else '0'
            hap1_val = '1' if hap1_winner else '0'
            
            hap0_cl = '0' if hap0_winner or not h0_losers else str(max(h0_losers))
            hap1_cl = '0' if hap1_winner or not h1_losers else str(max(h1_losers))
            
            s_out = [f"{hap0_val}|{hap1_val}"]
            if 'DS' in fmt_out: s_out.append(best_ds)
            if 'GP' in fmt_out: s_out.append(best_gp)
            if 'GQ' in fmt_out: s_out.append(str(best_gq) if best_gq != '.' else '.')
            if 'CL' in fmt_out: s_out.append(f"{hap0_cl},{hap1_cl}")
            
            vcf_line.append(':'.join(s_out))
            
        print('\t'.join(vcf_line))

cl_header_added = False
current_pos = None
group = []

for line in sys.stdin:
    if line.startswith('#'):
        # Only stripping out tags explicitly belonging to unrelated callers
        if any([i in line for i in ['INFO=<ID=AK', 'FORMAT=<ID=GL', 'FORMAT=<ID=KC']]):
            continue
        if line.startswith('#CHROM') and not cl_header_added:
            print('##FORMAT=<ID=CL,Number=2,Type=Integer,Description="Collision indicator array (Hap0,Hap1): 0=optimal, 1=lost by GP, 2=lost by parsimony, 3=lost by stable sort">')
            cl_header_added = True
        elif line.startswith('##FORMAT=') and not cl_header_added:
            print('##FORMAT=<ID=CL,Number=2,Type=Integer,Description="Collision indicator array (Hap0,Hap1): 0=optimal, 1=lost by GP, 2=lost by parsimony, 3=lost by stable sort">')
            cl_header_added = True
        print(line[:-1])
        continue
        
    fields = line.split('\t')
    if len(fields) < 2: continue
    pos = fields[1]
    
    if current_pos is None:
        current_pos = pos
        
    if pos != current_pos:
        process_group(group)
        group = [line]
        current_pos = pos
    else:
        group.append(line)
        
if group:
    process_group(group)
